export async function copyToClipboard(text) {
  const safeText = typeof text === 'string' ? text : '';

  if (!safeText.trim()) {
    return false;
  }

  await navigator.clipboard.writeText(safeText);
  return true;
}

export function buildReportText(data = {}) {
  const summary = data.summary || 'Not available';
  const findings = data.findings || 'Not available';
  const risk = data.risk || 'Not available';
  const recommendations = data.recommendations || 'Not available';

  return [
    'AI Multi-Agent Healthcare Report',
    '--------------------------------',
    '',
    'Summary:',
    summary,
    '',
    'Key Findings:',
    findings,
    '',
    'Risk Level:',
    risk,
    '',
    'Recommendations:',
    recommendations,
    '',
    '--------------------------------',
    'Generated by MediSync AI',
  ].join('\n');
}

export function downloadReport(data = {}) {
  return downloadReportTxt(data);
}

export function downloadReportTxt(data = {}) {
  const reportText = buildReportText(data);
  const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
  const baseName = getBaseFileName(data.fileName);
  downloadBlob(blob, `${baseName}.txt`);
}

export function downloadReportPdf(data = {}) {
  const reportText = buildReportText(data);
  const pdfBytes = createSimplePdf(reportText);
  const blob = new Blob([pdfBytes], { type: 'application/pdf' });
  const baseName = getBaseFileName(data.fileName);
  downloadBlob(blob, `${baseName}.pdf`);
}

function getBaseFileName(fileName = '') {
  return (fileName || 'healthcare-report')
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-z0-9-_]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    || 'healthcare-report';
}

function downloadBlob(blob, fileName) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function createSimplePdf(text) {
  const encoder = new TextEncoder();
  const pageWidth = 612;
  const pageHeight = 792;
  const marginLeft = 56;
  const marginTop = 56;
  const lineHeight = 16;
  const maxCharsPerLine = 78;
  const maxLinesPerPage = 40;

  const wrappedLines = wrapText(text, maxCharsPerLine);
  const pages = chunkLines(wrappedLines, maxLinesPerPage);
  const objects = [];

  objects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n');

  const pageObjectNumbers = pages.map((_, index) => 4 + (index * 2));
  objects.push(`2 0 obj\n<< /Type /Pages /Count ${pages.length} /Kids [${pageObjectNumbers.map((n) => `${n} 0 R`).join(' ')}] >>\nendobj\n`);
  objects.push('3 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n');

  pages.forEach((lines, index) => {
    const pageObjectNumber = 4 + (index * 2);
    const contentObjectNumber = pageObjectNumber + 1;
    const startY = pageHeight - marginTop;
    const commands = [
      'BT',
      '/F1 12 Tf',
      `${marginLeft} ${startY} Td`,
    ];

    lines.forEach((line, lineIndex) => {
      if (lineIndex > 0) {
        commands.push('T*');
      }
      commands.push(`(${escapePdfText(toPdfAscii(line))}) Tj`);
    });

    commands.push('ET');

    const stream = `${commands.join('\n')}\n`;
    const streamLength = encoder.encode(stream).length;

    objects.push(
      `${pageObjectNumber} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObjectNumber} 0 R >>\nendobj\n`
    );
    objects.push(
      `${contentObjectNumber} 0 obj\n<< /Length ${streamLength} >>\nstream\n${stream}endstream\nendobj\n`
    );
  });

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  objects.forEach((object) => {
    offsets.push(encoder.encode(pdf).length);
    pdf += object;
  });

  const xrefStart = encoder.encode(pdf).length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return encoder.encode(pdf);
}

function wrapText(text, maxCharsPerLine) {
  return (text || '')
    .split('\n')
    .flatMap((line) => wrapLine(line, maxCharsPerLine));
}

function wrapLine(line, maxCharsPerLine) {
  const normalizedLine = toPdfAscii(line || '');

  if (!normalizedLine.trim()) {
    return [''];
  }

  const words = normalizedLine.split(/\s+/);
  const lines = [];
  let currentLine = '';

  words.forEach((word) => {
    const candidate = currentLine ? `${currentLine} ${word}` : word;
    if (candidate.length <= maxCharsPerLine) {
      currentLine = candidate;
    } else {
      if (currentLine) {
        lines.push(currentLine);
      }
      currentLine = word;
    }
  });

  if (currentLine) {
    lines.push(currentLine);
  }

  return lines;
}

function chunkLines(lines, chunkSize) {
  const chunks = [];
  for (let index = 0; index < lines.length; index += chunkSize) {
    chunks.push(lines.slice(index, index + chunkSize));
  }
  return chunks.length ? chunks : [['']];
}

function escapePdfText(text) {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function toPdfAscii(text) {
  return String(text || '')
    .replace(/[^\x20-\x7E]/g, ' ')
    .replace(/\s+/g, ' ')
    .trimEnd();
}
